"""Add slug field to Category

Revision ID: 4a07500a3158
Revises: 
Create Date: 2025-04-11 08:39:15.947464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a07500a3158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('categories', sa.Column('slug', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'categories', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
